### PR TITLE
#84  - Refactor server

### PR DESCRIPTION
**Pull request by SirWellington**
Cleans things up a bit, sets them up for future updates

### CODE REVIEW

**Comment by SirWellington** [comment]
Can one of the admins verify this patch?

**Comment by cordhernandez** [comment]
damn yo look at all this java code

**Comment by cordhernandez** [comment]
b-e-a-utiful

**Comment by cordhernandez** [comment]
looks good to me 
I approve

**Comment by SirWellington** [comment]
All this java code should be looking more and more familiar!

**Pull request merged**
