### PR TITLE
Bugfix - duplicate stores

### LINKED ISSUE #61: Fix Duplicate Stores Issue
# What
Right now some of the stores are showing up twice. This is because we have multiple images for the stores.

# Why
This is a bug and it should not be like this; it is confusing to our users.

### PR DESCRIPTION
**Pull request by SirWellington**
Fixes #61

### CODE REVIEW

**Comment by SirWellington** [comment]
Can one of the admins verify this patch?

**Comment by SirWellington** [comment]
ok to test

**Comment by SirWellington** [comment]
add to whitelist

**Comment by cordhernandez** [comment]
@SirWellington looks good to me 👍🏽

**Comment by SirWellington** [comment]
Thanks! merging.

**Pull request merged**
